"""Add fund transfer system tables

Revision ID: 0ca9f87819bb
Revises: cdbb6a62d7a5
Create Date: 2025-09-22 04:27:40.653132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ca9f87819bb'
down_revision = 'cdbb6a62d7a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfer_limits',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('bubble_id', sa.String(), nullable=True),
    sa.Column('is_global', sa.Boolean(), nullable=False),
    sa.Column('daily_limit_cedis', sa.Integer(), nullable=False),
    sa.Column('monthly_limit_cedis', sa.Integer(), nullable=False),
    sa.Column('single_transfer_limit_cedis', sa.Integer(), nullable=False),
    sa.Column('daily_used_cedis', sa.Integer(), nullable=False),
    sa.Column('monthly_used_cedis', sa.Integer(), nullable=False),
    sa.Column('last_daily_reset', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_monthly_reset', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bubble_id'], ['bubbles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fund_transfers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=False),
    sa.Column('transfer_type', sa.Enum('PEER_TO_PEER', 'BULK_PURCHASE', 'LOAN', 'REPAYMENT', 'EMERGENCY', 'TRADE_PAYMENT', 'CONTRIBUTION', name='transfertype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', 'REJECTED', 'EXPIRED', name='transferstatus'), nullable=False),
    sa.Column('sender_id', sa.String(), nullable=False),
    sa.Column('recipient_id', sa.String(), nullable=False),
    sa.Column('bubble_id', sa.String(), nullable=False),
    sa.Column('amount_cedis', sa.Integer(), nullable=False),
    sa.Column('fee_cedis', sa.Integer(), nullable=False),
    sa.Column('total_amount_cedis', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reference_note', sa.String(length=100), nullable=True),
    sa.Column('approval_level', sa.Enum('NONE', 'RECIPIENT', 'ADMIN', 'OWNER', 'DUAL', name='approvallevel'), nullable=False),
    sa.Column('requires_recipient_approval', sa.Boolean(), nullable=False),
    sa.Column('requires_admin_approval', sa.Boolean(), nullable=False),
    sa.Column('recipient_approved', sa.Boolean(), nullable=False),
    sa.Column('recipient_approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('admin_approved', sa.Boolean(), nullable=False),
    sa.Column('admin_approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by_id', sa.String(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('sender_transaction_id', sa.String(), nullable=True),
    sa.Column('recipient_transaction_id', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('daily_limit_check', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('meta_data', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['bubble_id'], ['bubbles.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['recipient_transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_table('transfer_approvals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transfer_id', sa.String(), nullable=False),
    sa.Column('approver_id', sa.String(), nullable=False),
    sa.Column('approval_type', sa.String(length=20), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['transfer_id'], ['fund_transfers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transfer_approvals')
    op.drop_table('fund_transfers')
    op.drop_table('transfer_limits')
    # ### end Alembic commands ###
