"""Ensure order tables exist

Revision ID: 138b3bd2d37e
Revises: 5e38670b3f1b
Create Date: 2025-09-22 02:18:02.204422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '138b3bd2d37e'
down_revision = '5e38670b3f1b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
