"""Add cart and cart_items tables

Revision ID: 3b4f4ed75470
Revises: 69347b27783b
Create Date: 2025-09-22 01:55:27.462918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b4f4ed75470'
down_revision = '69347b27783b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
