"""Add messaging and review system tables

Revision ID: 74e791b0f92e
Revises: manual_fund_transfer
Create Date: 2025-09-22 14:28:34.557701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74e791b0f92e'
down_revision = 'manual_fund_transfer'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
