"""Add bubble models to registry

Revision ID: cdbb6a62d7a5
Revises: f0bba74a8e4f
Create Date: 2025-09-22 03:58:24.831950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdbb6a62d7a5'
down_revision = 'f0bba74a8e4f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bubbles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('bubble_type', sa.Enum('PRODUCT_BASED', 'LOCATION_BASED', 'FARMER_COOP', 'WHOLESALE', 'GENERAL', name='bubbletype'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', 'ARCHIVED', name='bubblestatus'), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('primary_products', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('max_members', sa.Integer(), nullable=False),
    sa.Column('fund_transfer_enabled', sa.Boolean(), nullable=False),
    sa.Column('min_fund_transfer', sa.Integer(), nullable=False),
    sa.Column('max_fund_transfer', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('created_by_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('total_transactions', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bubble_activities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('bubble_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('meta_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bubble_id'], ['bubbles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bubble_invitations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('bubble_id', sa.String(), nullable=False),
    sa.Column('inviter_id', sa.String(), nullable=False),
    sa.Column('invitee_id', sa.String(), nullable=True),
    sa.Column('invitee_email', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bubble_id'], ['bubbles.id'], ),
    sa.ForeignKeyConstraint(['invitee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['inviter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bubble_members',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('bubble_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MODERATOR', 'MEMBER', 'PENDING', name='memberrole'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'BANNED', 'LEFT', name='memberstatus'), nullable=False),
    sa.Column('can_invite', sa.Boolean(), nullable=False),
    sa.Column('can_post', sa.Boolean(), nullable=False),
    sa.Column('can_transfer_funds', sa.Boolean(), nullable=False),
    sa.Column('invited_by_id', sa.String(), nullable=True),
    sa.Column('invitation_message', sa.Text(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bubble_id'], ['bubbles.id'], ),
    sa.ForeignKeyConstraint(['invited_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bubble_members')
    op.drop_table('bubble_invitations')
    op.drop_table('bubble_activities')
    op.drop_table('bubbles')
    # ### end Alembic commands ###
