"""add_admin_system_tables

Revision ID: ed6464eebcd0
Revises: add_giftcards
Create Date: 2025-10-29 00:36:02.507904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed6464eebcd0'
down_revision = 'add_giftcards'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('supplier_code', sa.String(length=50), nullable=False),
    sa.Column('supplier_type', sa.Enum('FARMER', 'WHOLESALER', 'DISTRIBUTOR', 'MANUFACTURER', name='suppliertype'), nullable=False),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('alternative_phone', sa.String(length=20), nullable=True),
    sa.Column('location', sa.JSON(), nullable=True),
    sa.Column('business_registration', sa.String(length=100), nullable=True),
    sa.Column('tax_id', sa.String(length=100), nullable=True),
    sa.Column('payment_terms', sa.String(length=255), nullable=True),
    sa.Column('bank_details', sa.JSON(), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('total_supplies', sa.Integer(), nullable=False),
    sa.Column('on_time_delivery_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('quality_rating', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('verification_status', sa.Enum('PENDING', 'VERIFIED', 'SUSPENDED', 'REJECTED', name='supplierstatus'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('specialization', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_supply_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_name'), 'suppliers', ['name'], unique=False)
    op.create_index(op.f('ix_suppliers_supplier_code'), 'suppliers', ['supplier_code'], unique=True)
    op.create_table('admin_activity_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('admin_id', sa.String(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('request_method', sa.String(length=10), nullable=True),
    sa.Column('request_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_image_library',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.String(), nullable=True),
    sa.Column('image_data', sa.Text(), nullable=False),
    sa.Column('thumbnail', sa.Text(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_size_kb', sa.String(length=20), nullable=True),
    sa.Column('image_format', sa.String(length=10), nullable=True),
    sa.Column('width', sa.String(length=10), nullable=True),
    sa.Column('height', sa.String(length=10), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('usage_count', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('uploaded_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_image_library_product_name'), 'product_image_library', ['product_name'], unique=False)
    op.create_table('riders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('rider_code', sa.String(length=50), nullable=False),
    sa.Column('vehicle_type', sa.Enum('BICYCLE', 'MOTORCYCLE', 'TRICYCLE', 'VAN', 'TRUCK', 'FOOT', name='vehicletype'), nullable=False),
    sa.Column('vehicle_number', sa.String(length=50), nullable=True),
    sa.Column('vehicle_make_model', sa.String(length=100), nullable=True),
    sa.Column('vehicle_color', sa.String(length=50), nullable=True),
    sa.Column('license_number', sa.String(length=100), nullable=True),
    sa.Column('license_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('insurance_number', sa.String(length=100), nullable=True),
    sa.Column('insurance_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('alternative_phone', sa.String(length=20), nullable=True),
    sa.Column('emergency_contact', sa.JSON(), nullable=True),
    sa.Column('base_location', sa.JSON(), nullable=True),
    sa.Column('coverage_areas', sa.JSON(), nullable=True),
    sa.Column('current_status', sa.Enum('AVAILABLE', 'ON_DELIVERY', 'OFF_DUTY', 'UNAVAILABLE', 'SUSPENDED', name='riderstatus'), nullable=False),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('total_deliveries', sa.Integer(), nullable=False),
    sa.Column('successful_deliveries', sa.Integer(), nullable=False),
    sa.Column('failed_deliveries', sa.Integer(), nullable=False),
    sa.Column('cancelled_deliveries', sa.Integer(), nullable=False),
    sa.Column('average_delivery_time_minutes', sa.Integer(), nullable=False),
    sa.Column('on_time_delivery_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('commission_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('total_earnings', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_riders_rider_code'), 'riders', ['rider_code'], unique=True)
    op.create_table('product_views',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('viewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('referrer', sa.String(length=500), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('restock_orders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('supplier_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('quantity_ordered', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity_received', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('order_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expected_delivery_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_delivery_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'IN_TRANSIT', 'RECEIVED', 'CANCELLED', 'PARTIAL', name='restockstatus'), nullable=False),
    sa.Column('cost_per_unit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('shipping_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_status', sa.String(length=50), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('delivery_notes', sa.Text(), nullable=True),
    sa.Column('quality_check_notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('received_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['received_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restock_orders_order_number'), 'restock_orders', ['order_number'], unique=True)
    op.create_table('rider_locations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('rider_id', sa.String(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=False),
    sa.Column('accuracy', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('speed_kmh', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('heading', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('battery_level', sa.Integer(), nullable=True),
    sa.Column('network_type', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rider_id'], ['riders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_analytics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=True),
    sa.Column('category_id', sa.String(), nullable=True),
    sa.Column('quantity_sold', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('revenue_cedis', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.Column('cost_cedis', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.Column('profit_cedis', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.Column('orders_count', sa.Integer(), nullable=False),
    sa.Column('average_order_value_cedis', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.Column('unique_customers', sa.Integer(), nullable=False),
    sa.Column('new_customers', sa.Integer(), nullable=False),
    sa.Column('returning_customers', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_analytics_date'), 'sales_analytics', ['date'], unique=False)
    op.create_table('supplier_products',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('supplier_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('supply_capacity', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('minimum_order_quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('last_supply_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_expected_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_supplied', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_preferred', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('quality_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('warehouse_inventory',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('quantity_available', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity_reserved', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity_damaged', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reorder_level', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('reorder_quantity', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('location_in_warehouse', sa.String(length=100), nullable=True),
    sa.Column('zone', sa.String(length=50), nullable=True),
    sa.Column('received_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('batch_number', sa.String(length=100), nullable=True),
    sa.Column('supplier_id', sa.String(), nullable=True),
    sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_counted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_table('delivery_assignments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('rider_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ASSIGNED', 'ACCEPTED', 'PICKED_UP', 'IN_TRANSIT', 'ARRIVED', 'DELIVERED', 'FAILED', 'CANCELLED', 'RETURNED', name='deliverystatus'), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('picked_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('in_transit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arrived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pickup_location', sa.JSON(), nullable=True),
    sa.Column('delivery_location', sa.JSON(), nullable=True),
    sa.Column('estimated_distance_km', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('actual_distance_km', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('estimated_delivery_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_delivery_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('customer_signature', sa.Text(), nullable=True),
    sa.Column('proof_of_delivery', sa.JSON(), nullable=True),
    sa.Column('delivery_notes', sa.Text(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('customer_rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('customer_feedback', sa.Text(), nullable=True),
    sa.Column('delivery_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('rider_commission', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('special_instructions', sa.Text(), nullable=True),
    sa.Column('items_description', sa.Text(), nullable=True),
    sa.Column('assigned_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['rider_id'], ['riders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_table('inventory_movements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('inventory_id', sa.String(), nullable=True),
    sa.Column('movement_type', sa.Enum('IN', 'OUT', 'ADJUSTMENT', 'DAMAGED', 'EXPIRED', 'RETURNED', 'TRANSFER', name='movementtype'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('from_location', sa.String(length=100), nullable=True),
    sa.Column('to_location', sa.String(length=100), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.String(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('batch_number', sa.String(length=100), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('performed_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inventory_id'], ['warehouse_inventory.id'], ),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('inventory_id', sa.String(), nullable=True),
    sa.Column('alert_type', sa.Enum('LOW_STOCK', 'OUT_OF_STOCK', 'EXPIRING_SOON', 'EXPIRED', 'OVERSTOCKED', name='alerttype'), nullable=False),
    sa.Column('threshold_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('current_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'RESOLVED', 'DISMISSED', name='alertstatus'), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.String(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inventory_id'], ['warehouse_inventory.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('orders', sa.Column('rider_id', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('estimated_delivery_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('actual_delivery_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('delivery_rating', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('orders', sa.Column('delivery_feedback', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'orders', 'riders', ['rider_id'], ['id'])
    op.add_column('products', sa.Column('supplier_id', sa.String(), nullable=True))
    op.add_column('products', sa.Column('warehouse_location', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('products', sa.Column('margin_percentage', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('products', sa.Column('sku', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('barcode', sa.String(length=100), nullable=True))
    op.add_column('products', sa.Column('weight', sa.Numeric(precision=8, scale=2), nullable=True))
    op.add_column('products', sa.Column('dimensions', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('is_perishable', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('products', sa.Column('shelf_life_days', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.create_foreign_key(None, 'products', 'suppliers', ['supplier_id'], ['id'])
    op.add_column('users', sa.Column('account_status', sa.String(length=20), nullable=False, server_default='active'))
    op.add_column('users', sa.Column('suspension_reason', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_activity_at')
    op.drop_column('users', 'suspension_reason')
    op.drop_column('users', 'account_status')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_column('products', 'shelf_life_days')
    op.drop_column('products', 'is_perishable')
    op.drop_column('products', 'dimensions')
    op.drop_column('products', 'weight')
    op.drop_column('products', 'barcode')
    op.drop_column('products', 'sku')
    op.drop_column('products', 'margin_percentage')
    op.drop_column('products', 'cost_price')
    op.drop_column('products', 'warehouse_location')
    op.drop_column('products', 'supplier_id')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'delivery_feedback')
    op.drop_column('orders', 'delivery_rating')
    op.drop_column('orders', 'actual_delivery_time')
    op.drop_column('orders', 'estimated_delivery_time')
    op.drop_column('orders', 'rider_id')
    op.drop_table('stock_alerts')
    op.drop_table('inventory_movements')
    op.drop_table('delivery_assignments')
    op.drop_table('warehouse_inventory')
    op.drop_table('supplier_products')
    op.drop_index(op.f('ix_sales_analytics_date'), table_name='sales_analytics')
    op.drop_table('sales_analytics')
    op.drop_table('rider_locations')
    op.drop_index(op.f('ix_restock_orders_order_number'), table_name='restock_orders')
    op.drop_table('restock_orders')
    op.drop_table('product_views')
    op.drop_index(op.f('ix_riders_rider_code'), table_name='riders')
    op.drop_table('riders')
    op.drop_index(op.f('ix_product_image_library_product_name'), table_name='product_image_library')
    op.drop_table('product_image_library')
    op.drop_table('admin_activity_logs')
    op.drop_index(op.f('ix_suppliers_supplier_code'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_name'), table_name='suppliers')
    op.drop_table('suppliers')
    # ### end Alembic commands ###
