"""Add bubble system tables

Revision ID: f0bba74a8e4f
Revises: 153469f42fa9
Create Date: 2025-09-22 03:43:39.889890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0bba74a8e4f'
down_revision = '153469f42fa9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
